# declare a service

apiVersion: v1
kind: Service
metadata:
  name: apache-svc
  labels:
    app: hello-apache
    version: v1.1
    env: prod

# define and configure service to access port 8080
spec:
  type: NodePort
  ports:
  - port: 80
#    nodePort: 32500
    protocol: TCP
  selector:
    app: hello-apache
